import type { IngredientCatalogItem } from './domain';

export const ingredientCatalog: IngredientCatalogItem[] = [
  {
    id: 'oats',
    name: 'Rolled oats',
    category: 'grain',
    tags: ['breakfast', 'fiber'],
    nutritionPer100g: { calories: 389, proteinGrams: 16.9, fatGrams: 6.9, carbGrams: 66.3 },
  },
  {
    id: 'greek-yogurt',
    name: 'Greek yogurt',
    category: 'dairy',
    tags: ['protein', 'breakfast', 'snack'],
    nutritionPer100g: { calories: 97, proteinGrams: 10, fatGrams: 4, carbGrams: 3.9 },
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'fruit',
    tags: ['fruit', 'sweet'],
    nutritionPer100g: { calories: 57, proteinGrams: 0.7, fatGrams: 0.3, carbGrams: 14.5 },
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'fruit',
    tags: ['fruit', 'sweet'],
    nutritionPer100g: { calories: 89, proteinGrams: 1.1, fatGrams: 0.3, carbGrams: 22.8 },
  },
  {
    id: 'chia-seeds',
    name: 'Chia seeds',
    category: 'seed',
    tags: ['fiber', 'omega-3'],
    nutritionPer100g: { calories: 486, proteinGrams: 16.5, fatGrams: 30.7, carbGrams: 42.1 },
  },
  {
    id: 'eggs',
    name: 'Eggs',
    category: 'protein',
    tags: ['breakfast', 'protein'],
    nutritionPer100g: { calories: 143, proteinGrams: 12.6, fatGrams: 9.5, carbGrams: 0.7 },
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'vegetable',
    tags: ['greens', 'vegetable'],
    nutritionPer100g: { calories: 23, proteinGrams: 2.9, fatGrams: 0.4, carbGrams: 3.6 },
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'vegetable',
    tags: ['vegetable', 'fresh'],
    nutritionPer100g: { calories: 18, proteinGrams: 0.9, fatGrams: 0.2, carbGrams: 3.9 },
  },
  {
    id: 'olive-oil',
    name: 'Olive oil',
    category: 'fat',
    tags: ['fat', 'cooking'],
    nutritionPer100g: { calories: 884, proteinGrams: 0, fatGrams: 100, carbGrams: 0 },
  },
  {
    id: 'whole-grain-bread',
    name: 'Whole grain bread',
    category: 'grain',
    tags: ['breakfast', 'toast'],
    nutritionPer100g: { calories: 247, proteinGrams: 13, fatGrams: 4.2, carbGrams: 41 },
  },
  {
    id: 'mushrooms',
    name: 'Mushrooms',
    category: 'vegetable',
    tags: ['vegetable', 'savory'],
    nutritionPer100g: { calories: 22, proteinGrams: 3.1, fatGrams: 0.3, carbGrams: 3.3 },
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage cheese',
    category: 'dairy',
    tags: ['protein', 'snack'],
    nutritionPer100g: { calories: 98, proteinGrams: 11.1, fatGrams: 4.3, carbGrams: 3.4 },
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'fruit',
    tags: ['fruit', 'snack'],
    nutritionPer100g: { calories: 52, proteinGrams: 0.3, fatGrams: 0.2, carbGrams: 13.8 },
  },
  {
    id: 'chicken-breast',
    name: 'Chicken breast',
    category: 'protein',
    tags: ['protein', 'lean'],
    nutritionPer100g: { calories: 165, proteinGrams: 31, fatGrams: 3.6, carbGrams: 0 },
  },
  {
    id: 'brown-rice',
    name: 'Brown rice',
    category: 'grain',
    tags: ['grain', 'lunch', 'dinner'],
    nutritionPer100g: { calories: 111, proteinGrams: 2.6, fatGrams: 0.9, carbGrams: 23 },
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    category: 'grain',
    tags: ['grain', 'fiber'],
    nutritionPer100g: { calories: 120, proteinGrams: 4.4, fatGrams: 1.9, carbGrams: 21.3 },
  },
  {
    id: 'tuna',
    name: 'Tuna',
    category: 'protein',
    tags: ['protein', 'seafood'],
    nutritionPer100g: { calories: 116, proteinGrams: 26, fatGrams: 1, carbGrams: 0 },
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'vegetable',
    tags: ['vegetable', 'fresh'],
    nutritionPer100g: { calories: 15, proteinGrams: 0.7, fatGrams: 0.1, carbGrams: 3.6 },
  },
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'fat',
    tags: ['fat', 'fresh'],
    nutritionPer100g: { calories: 160, proteinGrams: 2, fatGrams: 14.7, carbGrams: 8.5 },
  },
  {
    id: 'turkey-mince',
    name: 'Lean turkey mince',
    category: 'protein',
    tags: ['protein', 'lean'],
    nutritionPer100g: { calories: 170, proteinGrams: 26, fatGrams: 7, carbGrams: 0 },
  },
  {
    id: 'whole-wheat-pasta',
    name: 'Whole wheat pasta',
    category: 'grain',
    tags: ['grain', 'comfort'],
    nutritionPer100g: { calories: 149, proteinGrams: 5.8, fatGrams: 0.9, carbGrams: 30.9 },
  },
  {
    id: 'tofu',
    name: 'Firm tofu',
    category: 'protein',
    tags: ['protein', 'plant-based'],
    nutritionPer100g: { calories: 144, proteinGrams: 17.3, fatGrams: 8.7, carbGrams: 2.8 },
  },
  {
    id: 'bell-pepper',
    name: 'Bell pepper',
    category: 'vegetable',
    tags: ['vegetable', 'fresh'],
    nutritionPer100g: { calories: 31, proteinGrams: 1, fatGrams: 0.3, carbGrams: 6 },
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'protein',
    tags: ['protein', 'seafood', 'omega-3'],
    nutritionPer100g: { calories: 208, proteinGrams: 20, fatGrams: 13, carbGrams: 0 },
  },
  {
    id: 'sweet-potato',
    name: 'Sweet potato',
    category: 'vegetable',
    tags: ['starch', 'dinner'],
    nutritionPer100g: { calories: 86, proteinGrams: 1.6, fatGrams: 0.1, carbGrams: 20.1 },
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas',
    category: 'legume',
    tags: ['legume', 'plant-based'],
    nutritionPer100g: { calories: 164, proteinGrams: 8.9, fatGrams: 2.6, carbGrams: 27.4 },
  },
  {
    id: 'black-beans',
    name: 'Black beans',
    category: 'legume',
    tags: ['legume', 'plant-based'],
    nutritionPer100g: { calories: 132, proteinGrams: 8.9, fatGrams: 0.5, carbGrams: 23.7 },
  },
  {
    id: 'carrots',
    name: 'Carrots',
    category: 'vegetable',
    tags: ['vegetable', 'snack'],
    nutritionPer100g: { calories: 41, proteinGrams: 0.9, fatGrams: 0.2, carbGrams: 9.6 },
  },
  {
    id: 'hummus',
    name: 'Hummus',
    category: 'spread',
    tags: ['snack', 'legume'],
    nutritionPer100g: { calories: 166, proteinGrams: 7.9, fatGrams: 9.6, carbGrams: 14.3 },
  },
  {
    id: 'peanut-butter',
    name: 'Peanut butter',
    category: 'spread',
    tags: ['peanut', 'allergen', 'spread'],
    nutritionPer100g: { calories: 588, proteinGrams: 25, fatGrams: 50, carbGrams: 20 },
  },
];

export const ingredientCatalogMap = new Map(
  ingredientCatalog.map((ingredient) => [ingredient.id, ingredient]),
);
