import type { MealTemplate } from './domain';

export const mealTemplates: MealTemplate[] = [
  {
    id: 'breakfast-overnight-oats',
    title: 'Berry overnight oats',
    slotType: 'breakfast',
    cuisine: 'Modern European',
    prepMinutes: 10,
    tags: ['breakfast', 'high-protein', 'meal-prep'],
    ingredients: [
      { ingredientId: 'oats', grams: 55 },
      { ingredientId: 'greek-yogurt', grams: 220 },
      { ingredientId: 'blueberries', grams: 90 },
      { ingredientId: 'banana', grams: 90 },
      { ingredientId: 'chia-seeds', grams: 12 },
    ],
    steps: [
      'Mix oats, yogurt, chia seeds, and sliced banana in a jar.',
      'Top with blueberries and chill overnight.',
      'Serve cold or let it sit at room temperature for five minutes.',
    ],
  },
  {
    id: 'breakfast-savory-eggs-toast',
    title: 'Savory eggs on toast',
    slotType: 'breakfast',
    cuisine: 'Mediterranean',
    prepMinutes: 15,
    tags: ['breakfast', 'savory', 'high-protein'],
    ingredients: [
      { ingredientId: 'eggs', grams: 140 },
      { ingredientId: 'spinach', grams: 70 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'whole-grain-bread', grams: 85 },
      { ingredientId: 'olive-oil', grams: 6 },
    ],
    steps: [
      'Saute spinach and tomato in olive oil.',
      'Scramble the eggs into the pan until just set.',
      'Serve on toasted whole grain bread.',
    ],
  },
  {
    id: 'breakfast-cottage-bowl',
    title: 'Cottage cheese power bowl',
    slotType: 'breakfast',
    cuisine: 'Nordic',
    prepMinutes: 8,
    tags: ['breakfast', 'high-protein', 'quick'],
    ingredients: [
      { ingredientId: 'cottage-cheese', grams: 240 },
      { ingredientId: 'apple', grams: 140 },
      { ingredientId: 'blueberries', grams: 70 },
      { ingredientId: 'oats', grams: 20 },
      { ingredientId: 'chia-seeds', grams: 10 },
    ],
    steps: [
      'Layer cottage cheese in a bowl.',
      'Add diced apple, blueberries, oats, and chia seeds on top.',
      'Mix just before eating.',
    ],
  },
  {
    id: 'breakfast-yogurt-parfait',
    title: 'Yogurt parfait with fruit',
    slotType: 'breakfast',
    cuisine: 'American',
    prepMinutes: 6,
    tags: ['breakfast', 'quick', 'high-protein'],
    ingredients: [
      { ingredientId: 'greek-yogurt', grams: 280 },
      { ingredientId: 'oats', grams: 35 },
      { ingredientId: 'banana', grams: 85 },
      { ingredientId: 'blueberries', grams: 80 },
    ],
    steps: [
      'Spoon yogurt into a glass or bowl.',
      'Layer oats and fruit over the yogurt.',
      'Serve immediately for crunch.',
    ],
  },
  {
    id: 'breakfast-omelette-quinoa',
    title: 'Veggie omelette with quinoa',
    slotType: 'breakfast',
    cuisine: 'Mediterranean',
    prepMinutes: 18,
    tags: ['breakfast', 'savory', 'balanced'],
    ingredients: [
      { ingredientId: 'eggs', grams: 150 },
      { ingredientId: 'spinach', grams: 80 },
      { ingredientId: 'mushrooms', grams: 90 },
      { ingredientId: 'tomato', grams: 80 },
      { ingredientId: 'quinoa', grams: 110 },
      { ingredientId: 'olive-oil', grams: 6 },
    ],
    steps: [
      'Saute mushrooms, spinach, and tomato in olive oil.',
      'Pour beaten eggs over the vegetables and cook into an omelette.',
      'Serve with warm quinoa on the side.',
    ],
  },
  {
    id: 'breakfast-avocado-egg-toast',
    title: 'Avocado egg toast',
    slotType: 'breakfast',
    cuisine: 'Californian',
    prepMinutes: 12,
    tags: ['breakfast', 'savory', 'quick'],
    ingredients: [
      { ingredientId: 'whole-grain-bread', grams: 85 },
      { ingredientId: 'avocado', grams: 70 },
      { ingredientId: 'eggs', grams: 130 },
      { ingredientId: 'tomato', grams: 70 },
    ],
    steps: [
      'Toast the bread.',
      'Mash avocado onto the toast and top with sliced tomato.',
      'Cook the eggs your preferred way and serve on top.',
    ],
  },
  {
    id: 'lunch-chicken-rice-bowl',
    title: 'Chicken rice bowl',
    slotType: 'lunch',
    cuisine: 'Balanced bowl',
    prepMinutes: 22,
    tags: ['lunch', 'high-protein', 'meal-prep'],
    ingredients: [
      { ingredientId: 'chicken-breast', grams: 165 },
      { ingredientId: 'brown-rice', grams: 190 },
      { ingredientId: 'spinach', grams: 60 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Cook the chicken until done and slice it.',
      'Serve over brown rice with spinach and tomato.',
      'Finish with a drizzle of olive oil.',
    ],
  },
  {
    id: 'lunch-tuna-quinoa-salad',
    title: 'Tuna quinoa salad',
    slotType: 'lunch',
    cuisine: 'Mediterranean',
    prepMinutes: 15,
    tags: ['lunch', 'high-protein', 'quick'],
    ingredients: [
      { ingredientId: 'tuna', grams: 150 },
      { ingredientId: 'quinoa', grams: 180 },
      { ingredientId: 'cucumber', grams: 110 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'avocado', grams: 50 },
      { ingredientId: 'olive-oil', grams: 6 },
    ],
    steps: [
      'Combine quinoa, tuna, cucumber, and tomato in a bowl.',
      'Fold in avocado pieces.',
      'Dress with olive oil just before serving.',
    ],
  },
  {
    id: 'lunch-turkey-pasta',
    title: 'Turkey pasta skillet',
    slotType: 'lunch',
    cuisine: 'Italian-inspired',
    prepMinutes: 25,
    tags: ['lunch', 'comfort', 'high-protein'],
    ingredients: [
      { ingredientId: 'turkey-mince', grams: 160 },
      { ingredientId: 'whole-wheat-pasta', grams: 210 },
      { ingredientId: 'tomato', grams: 130 },
      { ingredientId: 'spinach', grams: 70 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Brown the turkey mince in olive oil.',
      'Fold in chopped tomato and spinach until wilted.',
      'Toss through cooked whole wheat pasta.',
    ],
  },
  {
    id: 'lunch-tofu-stir-fry',
    title: 'Tofu veggie stir-fry',
    slotType: 'lunch',
    cuisine: 'Asian-inspired',
    prepMinutes: 20,
    tags: ['lunch', 'plant-based', 'balanced'],
    ingredients: [
      { ingredientId: 'tofu', grams: 190 },
      { ingredientId: 'brown-rice', grams: 175 },
      { ingredientId: 'bell-pepper', grams: 120 },
      { ingredientId: 'spinach', grams: 80 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Pan-sear tofu in olive oil until golden.',
      'Add bell pepper and spinach and cook until tender-crisp.',
      'Serve over brown rice.',
    ],
  },
  {
    id: 'lunch-chicken-chickpea-salad',
    title: 'Chicken chickpea salad',
    slotType: 'lunch',
    cuisine: 'Mediterranean',
    prepMinutes: 18,
    tags: ['lunch', 'high-protein', 'fresh'],
    ingredients: [
      { ingredientId: 'chicken-breast', grams: 150 },
      { ingredientId: 'chickpeas', grams: 120 },
      { ingredientId: 'cucumber', grams: 100 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'spinach', grams: 60 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Slice the cooked chicken.',
      'Combine chickpeas, cucumber, tomato, and spinach in a bowl.',
      'Top with chicken and olive oil.',
    ],
  },
  {
    id: 'lunch-black-bean-bowl',
    title: 'Black bean quinoa bowl',
    slotType: 'lunch',
    cuisine: 'Latin-inspired',
    prepMinutes: 16,
    tags: ['lunch', 'plant-based', 'fiber'],
    ingredients: [
      { ingredientId: 'black-beans', grams: 160 },
      { ingredientId: 'quinoa', grams: 170 },
      { ingredientId: 'bell-pepper', grams: 110 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'avocado', grams: 55 },
      { ingredientId: 'olive-oil', grams: 5 },
    ],
    steps: [
      'Warm the beans and quinoa together.',
      'Add chopped bell pepper and tomato.',
      'Finish with avocado and olive oil.',
    ],
  },
  {
    id: 'dinner-salmon-sweet-potato',
    title: 'Salmon with sweet potato',
    slotType: 'dinner',
    cuisine: 'Nordic',
    prepMinutes: 28,
    tags: ['dinner', 'omega-3', 'balanced'],
    ingredients: [
      { ingredientId: 'salmon', grams: 180 },
      { ingredientId: 'sweet-potato', grams: 260 },
      { ingredientId: 'spinach', grams: 80 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Roast the sweet potato until tender.',
      'Pan-sear or bake salmon until cooked through.',
      'Wilt spinach in olive oil and serve everything together.',
    ],
  },
  {
    id: 'dinner-chicken-quinoa',
    title: 'Chicken quinoa plate',
    slotType: 'dinner',
    cuisine: 'Balanced bowl',
    prepMinutes: 24,
    tags: ['dinner', 'high-protein', 'meal-prep'],
    ingredients: [
      { ingredientId: 'chicken-breast', grams: 175 },
      { ingredientId: 'quinoa', grams: 185 },
      { ingredientId: 'bell-pepper', grams: 110 },
      { ingredientId: 'tomato', grams: 90 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Cook the chicken and slice it.',
      'Serve with quinoa, bell pepper, and tomato.',
      'Finish with olive oil.',
    ],
  },
  {
    id: 'dinner-tofu-pasta',
    title: 'Tofu pasta bowl',
    slotType: 'dinner',
    cuisine: 'Italian-inspired',
    prepMinutes: 24,
    tags: ['dinner', 'plant-based', 'comfort'],
    ingredients: [
      { ingredientId: 'tofu', grams: 190 },
      { ingredientId: 'whole-wheat-pasta', grams: 190 },
      { ingredientId: 'tomato', grams: 130 },
      { ingredientId: 'spinach', grams: 70 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Brown tofu in olive oil.',
      'Add tomato and spinach and cook until the sauce comes together.',
      'Toss with cooked whole wheat pasta.',
    ],
  },
  {
    id: 'dinner-turkey-rice-bowl',
    title: 'Turkey rice bowl',
    slotType: 'dinner',
    cuisine: 'Latin-inspired',
    prepMinutes: 22,
    tags: ['dinner', 'high-protein', 'balanced'],
    ingredients: [
      { ingredientId: 'turkey-mince', grams: 165 },
      { ingredientId: 'brown-rice', grams: 185 },
      { ingredientId: 'bell-pepper', grams: 120 },
      { ingredientId: 'cucumber', grams: 90 },
      { ingredientId: 'avocado', grams: 45 },
      { ingredientId: 'olive-oil', grams: 6 },
    ],
    steps: [
      'Cook turkey mince until browned.',
      'Serve over rice with chopped vegetables.',
      'Top with avocado and olive oil.',
    ],
  },
  {
    id: 'dinner-tuna-potato-salad',
    title: 'Warm tuna potato salad',
    slotType: 'dinner',
    cuisine: 'Mediterranean',
    prepMinutes: 18,
    tags: ['dinner', 'high-protein', 'quick'],
    ingredients: [
      { ingredientId: 'tuna', grams: 160 },
      { ingredientId: 'sweet-potato', grams: 220 },
      { ingredientId: 'spinach', grams: 70 },
      { ingredientId: 'tomato', grams: 100 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Warm cooked sweet potato chunks.',
      'Combine with tuna, spinach, and tomato.',
      'Dress with olive oil.',
    ],
  },
  {
    id: 'dinner-chicken-chickpeas',
    title: 'Chicken and chickpea skillet',
    slotType: 'dinner',
    cuisine: 'Mediterranean',
    prepMinutes: 21,
    tags: ['dinner', 'high-protein', 'fiber'],
    ingredients: [
      { ingredientId: 'chicken-breast', grams: 160 },
      { ingredientId: 'chickpeas', grams: 140 },
      { ingredientId: 'tomato', grams: 120 },
      { ingredientId: 'spinach', grams: 80 },
      { ingredientId: 'olive-oil', grams: 8 },
    ],
    steps: [
      'Cook the chicken in olive oil.',
      'Add chickpeas and tomato and simmer briefly.',
      'Fold in spinach until wilted and serve.',
    ],
  },
  {
    id: 'snack-yogurt-berries',
    title: 'Greek yogurt and berries',
    slotType: 'snack',
    cuisine: 'Any',
    prepMinutes: 4,
    tags: ['snack', 'high-protein', 'quick'],
    ingredients: [
      { ingredientId: 'greek-yogurt', grams: 200 },
      { ingredientId: 'blueberries', grams: 90 },
    ],
    steps: ['Add yogurt to a bowl.', 'Top with blueberries.'],
  },
  {
    id: 'snack-cottage-apple',
    title: 'Cottage cheese with apple',
    slotType: 'snack',
    cuisine: 'Any',
    prepMinutes: 4,
    tags: ['snack', 'high-protein', 'quick'],
    ingredients: [
      { ingredientId: 'cottage-cheese', grams: 190 },
      { ingredientId: 'apple', grams: 130 },
    ],
    steps: ['Slice the apple.', 'Serve with cottage cheese.'],
  },
  {
    id: 'snack-hummus-crudites',
    title: 'Hummus and crunch veg',
    slotType: 'snack',
    cuisine: 'Mediterranean',
    prepMinutes: 6,
    tags: ['snack', 'fresh', 'fiber'],
    ingredients: [
      { ingredientId: 'hummus', grams: 90 },
      { ingredientId: 'carrots', grams: 120 },
      { ingredientId: 'cucumber', grams: 120 },
    ],
    steps: ['Slice carrots and cucumber into sticks.', 'Serve with hummus for dipping.'],
  },
  {
    id: 'snack-banana-yogurt-oats',
    title: 'Banana yogurt crunch',
    slotType: 'snack',
    cuisine: 'Any',
    prepMinutes: 5,
    tags: ['snack', 'quick', 'balanced'],
    ingredients: [
      { ingredientId: 'greek-yogurt', grams: 180 },
      { ingredientId: 'banana', grams: 100 },
      { ingredientId: 'oats', grams: 20 },
    ],
    steps: ['Spoon yogurt into a bowl.', 'Top with sliced banana and oats.'],
  },
];

export const slotTemplateMap = mealTemplates.reduce<Record<string, MealTemplate[]>>(
  (accumulator, template) => {
    accumulator[template.slotType] ??= [];
    accumulator[template.slotType].push(template);
    return accumulator;
  },
  {},
);
